# Generated by Django 4.2.11 on 2024-08-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('canceled', 'Canceled')], default='in_progress', max_length=20),
        ),
    ]
